version: '3.0'

services:

  # NGINX
  # - Reverse proxy to expose services
  #
  nginx:
    build: ./
    container_name: nginx
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - cps_acc
      - cps_prod
    volumes:
      - /var/log/nginx/:/var/log/nginx  
    ports:
      - 443:443
    expose:
      - 80  
    labels:
      cps.stack: "Proxy"
      cps.name: "NGINX reverse proxy"       
      cps.env: "global"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3  
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 15m  

networks:
  cps_acc:
     external: true
  cps_prod:
     external: true     
