version: '3.9'

services:

  #  Docker socket proxy
  #  Used by dashboard to show containers, future monitoring etc.
  #
  docker-proxy:
    container_name: docker-proxy
    image: tecnativa/docker-socket-proxy
    networks:
      - docker_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped  
    expose:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:  
      # Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.), 0 to revoke access / 1 to grant access.
      - CONTAINERS=1
      - INFO=1
      - SYSTEM=1
      - VOLUMES=1
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=0
      - NETWORKS=0
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0 # Portainer

    labels:
      cps.stack: "Dashboard"
      cps.name: "Docker proxy"
      cps.env: "global"

    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: 30s
      timeout: 2s
      retries: 3

networks:
  docker_proxy:
     external: true  
